<a href="https://colab.research.google.com/github/hwmishra/andol/blob/master/data_science_day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

### Broadcasting
* Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes

### NumPy 
* Numpy is the fundamental package for numerical computing with Python. It contains among other things:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

In [0]:
import numpy as np   # Importing libraries

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

print("Matrix A\n", a)
print("Matrix B\n", b)

print("Regular matrix addition A+B\n", a + b)

print("Addition using Broadcasting A+5\n", a + 5)

### Broadcasting Rules
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

1. they are equal, or
2.  one of them is 1

In [0]:
# Lets go for a 2D matrix
c = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
d = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])

e = np.array([1, 2, 3])

print("Matrix C\n", c)
print("Matrix D\n", d)
print("Matrix E\n", e)

print("Regular matrix addition C+D\n", c + d)

print("Addition using Broadcasting C+E\n", c + e)

Matrix C
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Matrix D
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Matrix E
 [1 2 3]
Regular matrix addition C+D
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
Addition using Broadcasting C+E
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]

In [0]:
M = np.ones((3, 3))
print("Matrix M:\n",M)

Matrix M:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [0]:
print("Dimension of M: ",M.shape)
print("Dimension of a: ",a.shape)
print("Addition using Broadcasting")
print(M + a)
# Broadcasting array with matrix

Dimension of M:  (3, 3)
Dimension of a:  (3,)
Addition using Broadcasting
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]

## All in one program

In [0]:
# Importing libraries
import timeit

# Usage of builtin functions
start = timeit.default_timer()   

# Defining a list
array_list = [10,11,15,19,21,32]      
array_np_list = []

# Print the list
print("Original List",array_list,"\n")   

# Defining a function
def prime(num):      
    if num > 1:     
        
        # check for factors
        # Iterating a range of numbers
        for i in range(2,num):    
            if (num % i) == 0:
                
                # Appending data to list
                array_np_list.append(num)           
                print(num,"is not a prime number (",i,"times",num//i,"is",num,")")
                
                # Terminating a loop run
                break         
        else:
            print(num,"is a prime number")
            
# Iterating a list
for item in array_list:
    
    # Calling a function
    prime(item)         

print("\nNon-prime List",array_np_list,"\n")

end = timeit.default_timer()

# Computing running time
print("Time Taken to run the program:",end - start, "seconds")

Original List [10, 11, 15, 19, 21, 32]

10 is not a prime number ( 2 times 5 is 10 )
11 is a prime number
15 is not a prime number ( 3 times 5 is 15 )
19 is a prime number
21 is not a prime number ( 3 times 7 is 21 )
32 is not a prime number ( 2 times 16 is 32 )

Non-prime List [10, 15, 21, 32]

Time Taken to run the program: 0.004166599999962273 seconds

### Note:
* Python is a procedural Language
* Two versions of Python 2 vs 3
* No braces. i.e. indentation
* No need to explicitly mention data type

## Unvectorized vs Vectorized Implementations

In [0]:
# Importing libraries
import numpy as np

# Defining matrices
mat_a = [[6, 7, 8],[5, 4, 5],[1, 1, 1]]
mat_b = [[1, 2, 3],[1, 2, 3],[1, 2, 3]]

# Getting a row from matrix
def get_row(matrix, row):
    return matrix[row]

# Getting a coloumn from matrix
def get_column(matrix, column_number):
    column = []
 
    for i in range(len(matrix)):
        column.append(matrix[i][column_number])
 
    return column

# Multiply a row with coloumn
def unv_dot_product(vector_one, vector_two):
    total = 0
 
    if len(vector_one) != len(vector_two):
        return total
 
    for i in range(len(vector_one)):
        product = vector_one[i] * vector_two[i]
        total += product
 
    return total

# Multiply two matrixes
def matrix_multiplication(matrix_one, matrix_two):
    m_rows = len(matrix_one)
    p_columns = len(matrix_two[0])
    result = []
    
    for i in range(m_rows):
        row_result = []
 
        for j in range(p_columns):
            row = get_row(matrix_one, i)
            column = get_column(matrix_two, j)
            product = unv_dot_product(row, column)
            
            row_result.append(product) 
        result.append(row_result)
        
    return result

print("Matrix A: ", mat_a,"\n")
print("Matrix B: ", mat_b,"\n")

print("Unvectorized Matrix Multiplication\n",matrix_multiplication(mat_a,mat_b),"\n")

Matrix A:  [[6, 7, 8], [5, 4, 5], [1, 1, 1]]

Matrix B:  [[1, 2, 3], [1, 2, 3], [1, 2, 3]]

Unvectorized Matrix Multiplication
 [[21, 42, 63], [14, 28, 42], [3, 6, 9]]

In [0]:
# Vectorized Implementation
npm_a = np.array(mat_a)
npm_b = np.array(mat_b)

print("Vectorized Matrix Multiplication\n",npm_a.dot(npm_b),"\n") 
# A.dot(B) is a numpy built-in function for dot product

Vectorized Matrix Multiplication
 [[21 42 63]
 [14 28 42]
 [ 3  6  9]]

### Tip:
* Vectorization reduces number of lines of code
* Always prefer libraries and avoid coding from scratch

## Essential Python Packages: Numpy, Pandas, Matplotlib

In [0]:
# Load library
import numpy as np

In [0]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
print("Vector:",vector)

# Select second element
print("Element 2 in Vector is",vector[1])

Vector: [1 2 3 4 5 6]
Element 2 in Vector is 2

In [0]:
np.flatten

In [0]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix\n",matrix)

# Select second row
print("Second row of Matrix\n",matrix[1,:])
print("Third coloumn of Matrix\n",matrix[:,2])

Matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second row of Matrix
 [4 5 6]
Third coloumn of Matrix
 [3 6 9]

In [0]:
# Create Tensor
tensor = np.array([ [[[1, 1], [1, 1]], [[2, 2], [2, 2]]],
                    [[[3, 3], [3, 3]], [[4, 4], [4, 4]]] ])

print("Tensor\n",tensor.shape)

Tensor
 (2, 2, 2, 2)

### Matrix properties

In [0]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix Shape:",matrix.shape)
print("Number of elements:",matrix.size)
print("Number of dimentions:",matrix.ndim)
print("Average of matrix:",np.mean(matrix))
print("Maximum number:",np.max(matrix))
print("Coloumn with minimum numbers:",np.min(matrix, axis=1))
print("Diagnol of matrix:",matrix.diagonal())
print("Determinant of matrix:",np.linalg.det(matrix))

Matrix Shape: (3, 3)
Number of elements: 9
Number of dimentions: 2
Average of matrix: 5.0
Maximum number: 9
Coloumn with minimum numbers: [1 4 7]
Diagnol of matrix: [1 5 9]
Determinant of matrix: 0.0

### Matrix Operations

In [0]:
print("Flattened Matrix\n",matrix.flatten())
print("Reshaping Matrix\n",matrix.reshape(9,1))
print("Transposed Matrix\n",matrix.T)

Flattened Matrix
 [1 2 3 4 5 6 7 8 9]
Reshaping Matrix
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Transposed Matrix
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

In [0]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

print("Matrix Addition\n",np.add(matrix_a, matrix_b))
print("Scalar Multiplication\n",np.multiply(matrix_a, matrix_b))
print("Matrix Multiplication\n",np.dot(matrix_a, matrix_b))

Matrix Addition
 [[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
Scalar Multiplication
 [[ 1  3  1]
 [ 1  3  1]
 [ 1  3 16]]
Matrix Multiplication
 [[ 3  9 10]
 [ 3  9 10]
 [ 4 12 18]]

In [0]:
x = np.arange(5) 
print(x)

In [0]:
x = np.arange(5, dtype = float)
print(x)

In [0]:
# numbers with difference of 2
x = np.arange(10,20,2) 
print x

In [0]:
x = np.linspace(10,20,5) 
print(x)

##let's get a rid of statistics with numpy

In [0]:
# X is a Python List
X = [32.32, 56.98, 21.52, 44.32, 55.63, 13.75, 43.47, 43.34]

# Sorting the data and printing it.
X.sort()
print(X)
# [13.75, 21.52, 32.32, 43.34, 43.47, 44.32, 55.63, 56.98]

# Using NumPy's built-in functions to Find Mean, Median, SD and Variance
mean = np.mean(X)
median = np.median(X)
sd = np.std(X)
variance = np.var(X)

# Printing the values
print("Mean", mean) # 38.91625
print("Median", median) # 43.405
print("Standard Deviation", sd) # 14.3815654029
print("Variance", variance) # 206.829423437

###The tool min returns the minimum value along a given axis.

In [0]:
x =np.arrange()

In [0]:
my_array = np.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print np.min(my_array, axis = 0)         #Output : [1 0]
print np.min(my_array, axis = 1)         #Output : [2 3 1 0]
print np.min(my_array, axis = None)      #Output : 0
print np.min(my_array)                   #Output : 0

###The tool max returns the maximum value along a given axis.

In [0]:
my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print np.max(my_array, axis = 0)         #Output : [4 7]
print np.max(my_array, axis = 1)         #Output : [5 7 3 4]
print np.max(my_array, axis = None)      #Output : 7
print np.max(my_array)                   #Output : 7

In [0]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

#NumPy Challenge
### You are given a 2-D array with dimensions N X M.
### Your task is to perform the min function over axis 1 and then find the max of that.
Sample Input

```
4 2
2 5
3 7
1 3
4 0
```

This is formatted as code

Sample Output

3

### Pandas

In [0]:
import pandas as pd

In [0]:
df=pd.read_csv("Income.csv", encoding="ISO-8859-1")
print("Data\n")
df

In [5]:
df.columns
df

Index(['id', 'State_Code', 'State_Name', 'State_ab', 'County', 'City', 'Place',
       'Type', 'Primary', 'Zip_Code', 'Area_Code', 'ALand', 'AWater', 'Lat',
       'Lon', 'Mean', 'Median', 'Stdev', 'sum_w'],
      dtype='object')

In [10]:
df[['State_Name','State_Code']]

        State_Name  State_Code
0          Alabama           1
1          Alabama           1
2          Alabama           1
3          Alabama           1
4          Alabama           1
5          Alabama           1
6          Alabama           1
7          Alabama           1
8          Alabama           1
9          Alabama           1
10         Alabama           1
11         Alabama           1
12         Alabama           1
13         Alabama           1
14         Alabama           1
15         Alabama           1
16         Alabama           1
17         Alabama           1
18         Alabama           1
19         Alabama           1
20         Alabama           1
21         Alabama           1
22         Alabama           1
23         Alabama           1
24         Alabama           1
25         Alabama           1
26         Alabama           1
27         Alabama           1
28         Alabama           1
29         Alabama           1
...            ...         ...
32496  Puerto Rico          72
32497  Puerto Rico          72
32498  Puerto Rico          72
32499  Puerto Rico          72
32500  Puerto Rico          72
32501  Puerto Rico          72
32502  Puerto Rico          72
32503  Puerto Rico          72
32504  Puerto Rico          72
32505  Puerto Rico          72
32506  Puerto Rico          72
32507  Puerto Rico          72
32508  Puerto Rico          72
32509  Puerto Rico          72
32510  Puerto Rico          72
32511  Puerto Rico          72
32512  Puerto Rico          72
32513  Puerto Rico          72
32514  Puerto Rico          72
32515  Puerto Rico          72
32516  Puerto Rico          72
32517  Puerto Rico          72
32518  Puerto Rico          72
32519  Puerto Rico          72
32520  Puerto Rico          72
32521  Puerto Rico          72
32522  Puerto Rico          72
32523  Puerto Rico          72
32524  Puerto Rico          72
32525  Puerto Rico          72

[32526 rows x 2 columns]

In [12]:
df[:5]

        id  State_Code State_Name State_ab  ...   Mean Median  Stdev        sum_w
0  1011000           1    Alabama       AL  ...  38773  30506  33101  1638.260513
1  1011010           1    Alabama       AL  ...  37725  19528  43789   258.017685
2  1011020           1    Alabama       AL  ...  54606  31930  57348   926.031000
3  1011030           1    Alabama       AL  ...  63919  52814  47707   378.114619
4  1011040           1    Alabama       AL  ...  77948  67225  54270   282.320328

[5 rows x 19 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32526 entries, 0 to 32525
Data columns (total 19 columns):
id            32526 non-null int64
State_Code    32526 non-null int64
State_Name    32526 non-null object
State_ab      32526 non-null object
County        32526 non-null object
City          32526 non-null object
Place         32526 non-null object
Type          32526 non-null object
Primary       32526 non-null object
Zip_Code      32526 non-null int64
Area_Code     32526 non-null object
ALand         32526 non-null int64
AWater        32526 non-null int64
Lat           32526 non-null float64
Lon           32526 non-null float64
Mean          32526 non-null int64
Median        32526 non-null int64
Stdev         32526 non-null int64
sum_w         32526 non-null float64
dtypes: float64(3), int64(8), object(8)
memory usage: 4.7+ MB

In [0]:
print("Top Elements\n")
df.head(3)

Top Elements

,GEOID,State,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,04000US01,Alabama,37150,37952,42212,44476,39980,40933,42590,43464,41381
1,04000US02,Alaska,55891,56418,62993,63989,61604,57848,57431,63648,61137
2,04000US04,Arizona,45245,46657,47215,46914,45739,46896,48621,47044,50602

In [0]:
print("Bottom Elements\n")
df.tail(3)

Bottom Elements

,GEOID,State,2005,2006,2007,2008,2009,2010,2011,2012,2013
3,04000US05,Arkansas,36658,37057,40795,39586,36538,38587,41302,39018,39919
4,04000US06,California,51755,55319,55734,57014,56134,54283,53367,57020,57528
5,04000US07,Chicago,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [0]:
print("Specific Coloumn\n")
df['State'].head(3)

Specific Coloumn

0    Alabama
1     Alaska
2    Arizona
Name: State, dtype: object

In [0]:
print("Replace negative numbers with NaN\n")
df.replace(-999,np.nan)

Replace negative numbers with NaN

,GEOID,State,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,04000US01,Alabama,37150.0,37952.0,42212.0,44476.0,39980.0,40933.0,42590.0,43464.0,41381.0
1,04000US02,Alaska,55891.0,56418.0,62993.0,63989.0,61604.0,57848.0,57431.0,63648.0,61137.0
2,04000US04,Arizona,45245.0,46657.0,47215.0,46914.0,45739.0,46896.0,48621.0,47044.0,50602.0
3,04000US05,Arkansas,36658.0,37057.0,40795.0,39586.0,36538.0,38587.0,41302.0,39018.0,39919.0
4,04000US06,California,51755.0,55319.0,55734.0,57014.0,56134.0,54283.0,53367.0,57020.0,57528.0
5,04000US07,Chicago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df['State_ab'].value_counts()

CA    3280
TX    2300
NY    2160
FL    1661
PA    1475
IL    1431
OH    1349
MI    1174
NC     915
NJ     888
GA     818
VA     785
IN     704
MO     700
WA     688
WI     674
MA     670
MN     641
AZ     617
TN     610
MD     586
CO     526
AL     526
LA     511
KY     497
OK     480
SC     459
IA     454
OR     387
KS     381
PR     380
CT     355
AR     340
MS     321
NE     275
NV     265
UT     261
WV     248
NM     240
ME     157
ID     149
MT     148
HI     138
NH     131
SD     128
ND     119
RI     109
AK     105
DE      88
VT      83
WY      75
DC      64
Name: State_ab, dtype: int64

In [21]:
df[df['id']>101130]

            id  State_Code   State_Name  ...  Median  Stdev         sum_w
0      1011000           1      Alabama  ...   30506  33101   1638.260513
1      1011010           1      Alabama  ...   19528  43789    258.017685
2      1011020           1      Alabama  ...   31930  57348    926.031000
3      1011030           1      Alabama  ...   52814  47707    378.114619
4      1011040           1      Alabama  ...   67225  54270    282.320328
5      1011050           1      Alabama  ...   42643  35886    173.325959
6      1011060           1      Alabama  ...   23610  28256    758.771322
7      1011070           1      Alabama  ...   40242  38941    397.052564
8      1011080           1      Alabama  ...   39591  47235    137.496039
9      1011090           1      Alabama  ...   41712  51359    380.728238
10     1011100           1      Alabama  ...   38947  44430   3621.630319
11     1011110           1      Alabama  ...   28811  41397  10716.139237
12     1011120           1      Alabama  ...   19757  27656    553.438214
13     1011130           1      Alabama  ...   22745  27452    528.084885
14     1011140           1      Alabama  ...   21136  45043    775.252485
15     1011150           1      Alabama  ...   39047  53934     37.264332
16     1011160           1      Alabama  ...   21608  45280    770.565839
17     1011170           1      Alabama  ...  300000  55763    359.444828
18     1011180           1      Alabama  ...   46738  44401   1140.748190
19     1011190           1      Alabama  ...   34049  48287     77.397421
20     1011200           1      Alabama  ...  300000  28590    179.827252
21     1011210           1      Alabama  ...   34725  36562    152.195391
22     1011220           1      Alabama  ...   31635  62581     65.431457
23     1011230           1      Alabama  ...   43794  32431     46.199004
24     1011240           1      Alabama  ...   36849  45634    129.828638
25     1011250           1      Alabama  ...   48713  54529     74.131382
26     1011260           1      Alabama  ...   30427  38304    210.190640
27     1011270           1      Alabama  ...   39817  37964   1376.651180
28     1011280           1      Alabama  ...   38231  50855  51243.648369
29     1011290           1      Alabama  ...   28180  39942   1081.054675
...        ...         ...          ...  ...     ...    ...           ...
32496  7202736          72  Puerto Rico  ...   21595  33560   1183.992941
32497  7202746          72  Puerto Rico  ...   31311  49033   1259.033425
32498  7202756          72  Puerto Rico  ...   14894  23159   1741.112512
32499   720276          72  Puerto Rico  ...   15047  20368   1411.421601
32500  7202766          72  Puerto Rico  ...   37947  51297    576.307747
32501  7202776          72  Puerto Rico  ...   37852  32505    624.040183
32502  7202786          72  Puerto Rico  ...   23763  47278   1280.901137
32503  7202796          72  Puerto Rico  ...   22736  40510   1653.723378
32504  7202806          72  Puerto Rico  ...    4790   2451     19.996000
32505  7202816          72  Puerto Rico  ...   11755  16254    934.735832
32506  7202826          72  Puerto Rico  ...   13535  27901   1339.927633
32507  7202836          72  Puerto Rico  ...   19218  25434    632.931730
32508  7202846          72  Puerto Rico  ...   26058  30074   1084.881679
32509  7202856          72  Puerto Rico  ...   15540  22772   1034.556584
32510   720286          72  Puerto Rico  ...   14386  17794   2243.225575
32511  7202866          72  Puerto Rico  ...   43340  37995    919.382495
32512  7202876          72  Puerto Rico  ...   20295  32759   1342.935713
32513  7202886          72  Puerto Rico  ...   21260  30943   1112.018969
32514  7202896          72  Puerto Rico  ...   15197  23637   1433.965484
32515  7202906          72  Puerto Rico  ...   18989  21314   1041.797454
32516  7202916          72  Puerto Rico  ...       0      0      0.000000
32517  7202926          72  Puerto Rico  ...   17902  24082   1899.856852
32518  7202936          72  Puerto Rico  ...    8752  27699    801.619932
32519  7202946          72  Puerto Rico  ...    9378  21654    524.345149
32520  7202956          72  Puerto Rico  ...   15051  30309    615.289902
32521   720296          72  Puerto Rico  ...   13729  37977   1321.278082
32522  7202966          72  Puerto Rico  ...    9923  15541    238.813450
32523  7202976          72  Puerto Rico  ...   34054  31539    313.551070
32524  7202986          72  Puerto Rico  ...       0      0      0.000000
32525  7202996          72  Puerto Rico  ...   20229  33333    512.884803

[32408 rows x 19 columns]

In [22]:
query = df['id']>101130
df[query]

            id  State_Code   State_Name  ...  Median  Stdev         sum_w
0      1011000           1      Alabama  ...   30506  33101   1638.260513
1      1011010           1      Alabama  ...   19528  43789    258.017685
2      1011020           1      Alabama  ...   31930  57348    926.031000
3      1011030           1      Alabama  ...   52814  47707    378.114619
4      1011040           1      Alabama  ...   67225  54270    282.320328
5      1011050           1      Alabama  ...   42643  35886    173.325959
6      1011060           1      Alabama  ...   23610  28256    758.771322
7      1011070           1      Alabama  ...   40242  38941    397.052564
8      1011080           1      Alabama  ...   39591  47235    137.496039
9      1011090           1      Alabama  ...   41712  51359    380.728238
10     1011100           1      Alabama  ...   38947  44430   3621.630319
11     1011110           1      Alabama  ...   28811  41397  10716.139237
12     1011120           1      Alabama  ...   19757  27656    553.438214
13     1011130           1      Alabama  ...   22745  27452    528.084885
14     1011140           1      Alabama  ...   21136  45043    775.252485
15     1011150           1      Alabama  ...   39047  53934     37.264332
16     1011160           1      Alabama  ...   21608  45280    770.565839
17     1011170           1      Alabama  ...  300000  55763    359.444828
18     1011180           1      Alabama  ...   46738  44401   1140.748190
19     1011190           1      Alabama  ...   34049  48287     77.397421
20     1011200           1      Alabama  ...  300000  28590    179.827252
21     1011210           1      Alabama  ...   34725  36562    152.195391
22     1011220           1      Alabama  ...   31635  62581     65.431457
23     1011230           1      Alabama  ...   43794  32431     46.199004
24     1011240           1      Alabama  ...   36849  45634    129.828638
25     1011250           1      Alabama  ...   48713  54529     74.131382
26     1011260           1      Alabama  ...   30427  38304    210.190640
27     1011270           1      Alabama  ...   39817  37964   1376.651180
28     1011280           1      Alabama  ...   38231  50855  51243.648369
29     1011290           1      Alabama  ...   28180  39942   1081.054675
...        ...         ...          ...  ...     ...    ...           ...
32496  7202736          72  Puerto Rico  ...   21595  33560   1183.992941
32497  7202746          72  Puerto Rico  ...   31311  49033   1259.033425
32498  7202756          72  Puerto Rico  ...   14894  23159   1741.112512
32499   720276          72  Puerto Rico  ...   15047  20368   1411.421601
32500  7202766          72  Puerto Rico  ...   37947  51297    576.307747
32501  7202776          72  Puerto Rico  ...   37852  32505    624.040183
32502  7202786          72  Puerto Rico  ...   23763  47278   1280.901137
32503  7202796          72  Puerto Rico  ...   22736  40510   1653.723378
32504  7202806          72  Puerto Rico  ...    4790   2451     19.996000
32505  7202816          72  Puerto Rico  ...   11755  16254    934.735832
32506  7202826          72  Puerto Rico  ...   13535  27901   1339.927633
32507  7202836          72  Puerto Rico  ...   19218  25434    632.931730
32508  7202846          72  Puerto Rico  ...   26058  30074   1084.881679
32509  7202856          72  Puerto Rico  ...   15540  22772   1034.556584
32510   720286          72  Puerto Rico  ...   14386  17794   2243.225575
32511  7202866          72  Puerto Rico  ...   43340  37995    919.382495
32512  7202876          72  Puerto Rico  ...   20295  32759   1342.935713
32513  7202886          72  Puerto Rico  ...   21260  30943   1112.018969
32514  7202896          72  Puerto Rico  ...   15197  23637   1433.965484
32515  7202906          72  Puerto Rico  ...   18989  21314   1041.797454
32516  7202916          72  Puerto Rico  ...       0      0      0.000000
32517  7202926          72  Puerto Rico  ...   17902  24082   1899.856852
32518  7202936          72  Puerto Rico  ...    8752  27699    801.619932
32519  7202946          72  Puerto Rico  ...    9378  21654    524.345149
32520  7202956          72  Puerto Rico  ...   15051  30309    615.289902
32521   720296          72  Puerto Rico  ...   13729  37977   1321.278082
32522  7202966          72  Puerto Rico  ...    9923  15541    238.813450
32523  7202976          72  Puerto Rico  ...   34054  31539    313.551070
32524  7202986          72  Puerto Rico  ...       0      0      0.000000
32525  7202996          72  Puerto Rico  ...   20229  33333    512.884803

[32408 rows x 19 columns]

In [24]:
q1 =df['id']>101130
q2 = df['id']<1011040
df[(q1) & (q2)]

            id  State_Code     State_Name  ...  Median  Stdev         sum_w
0      1011000           1        Alabama  ...   30506  33101   1638.260513
1      1011010           1        Alabama  ...   19528  43789    258.017685
2      1011020           1        Alabama  ...   31930  57348    926.031000
3      1011030           1        Alabama  ...   52814  47707    378.114619
54      101901           1        Alabama  ...   11398  10903     47.998400
55      101910           1        Alabama  ...   20997  28311   1057.617393
56      101920           1        Alabama  ...  300000  25317      1.133107
57      101930           1        Alabama  ...   38029  60946  13447.913832
58      101940           1        Alabama  ...   35147  43788    519.274814
59      101950           1        Alabama  ...   29150  38565   7625.528576
60      101960           1        Alabama  ...   12379  58584    196.086835
61      101970           1        Alabama  ...   25776  27149    334.951746
62      101980           1        Alabama  ...   64695  38729   2521.942894
63      101990           1        Alabama  ...   27321  44007    239.687293
70      102106           1        Alabama  ...   54091  47663   1009.159632
81      102116           1        Alabama  ...   23009  38779   1174.454588
92      102126           1        Alabama  ...   41768  48428   1636.799960
103     102136           1        Alabama  ...   39956  48887   1013.526324
114     102146           1        Alabama  ...   30601  39286    386.135397
125     102156           1        Alabama  ...   35327  39518    518.148434
137     102166           1        Alabama  ...   84211  56279   1360.078197
148     102176           1        Alabama  ...   56246  44831   1277.268799
159     102186           1        Alabama  ...   16878  39063    540.009841
170     102196           1        Alabama  ...   26135  46568    569.205878
181     102206           1        Alabama  ...   47797  40234    442.911894
192     102216           1        Alabama  ...   38743  40883    951.471494
203     102226           1        Alabama  ...   53463  53245   1213.321946
214     102236           1        Alabama  ...   42647  33653    866.004405
225     102246           1        Alabama  ...   25083  33276   1098.668639
236     102256           1        Alabama  ...   25986  38026    487.181228
...        ...         ...            ...  ...     ...    ...           ...
31364   540270          54  West Virginia  ...   43644  37115    905.626316
31375   540280          54  West Virginia  ...   33906  36681   1249.995987
31386   540290          54  West Virginia  ...   33184  34030   1157.459456
31569   550218          55      Wisconsin  ...   47757  40319   1092.926062
31680   550228          55      Wisconsin  ...   49548  47841   1029.760951
31791   550238          55      Wisconsin  ...   41549  37709    805.134040
31902   550248          55      Wisconsin  ...   29571  30137   1908.812913
32013   550258          55      Wisconsin  ...   52882  49088   1256.517513
32034   550268          55      Wisconsin  ...   69106  62025   1330.337066
32045   550278          55      Wisconsin  ...   52378  51591    639.340936
32057   550288          55      Wisconsin  ...   49234  45484    597.642587
32068   550298          55      Wisconsin  ...   58936  44461    817.330556
32096   560214          56        Wyoming  ...   88491  58476   1351.501707
32107   560224          56        Wyoming  ...   59924  46488    751.590594
32118   560234          56        Wyoming  ...   63075  58180    983.415530
32130   560244          56        Wyoming  ...   42475  48980   1348.224224
32141   560254          56        Wyoming  ...   69614  48349   1523.992586
32142   560264          56        Wyoming  ...   68371  55082    502.709324
32143   560274          56        Wyoming  ...   70752  52272    679.859784
32144   560284          56        Wyoming  ...   79809  59325    683.900358
32145   560294          56        Wyoming  ...   64557  46315    988.182310
32238   720216          72    Puerto Rico  ...       0      0      0.000000
32349   720226          72    Puerto Rico  ...   11503  26576    488.534114
32454   720236          72    Puerto Rico  ...   12038  21332    899.071881
32465   720246          72    Puerto Rico  ...   17387  17996    990.551528
32476   720256          72    Puerto Rico  ...   21139  20942   1023.249808
32488   720266          72    Puerto Rico  ...    6264  15055    956.933065
32499   720276          72    Puerto Rico  ...   15047  20368   1411.421601
32510   720286          72    Puerto Rico  ...   14386  17794   2243.225575
32521   720296          72    Puerto Rico  ...   13729  37977   1321.278082

[1250 rows x 19 columns]

In [30]:
df[df['id']>101130]['id']

0        1011000
1        1011010
2        1011020
3        1011030
4        1011040
5        1011050
6        1011060
7        1011070
8        1011080
9        1011090
10       1011100
11       1011110
12       1011120
13       1011130
14       1011140
15       1011150
16       1011160
17       1011170
18       1011180
19       1011190
20       1011200
21       1011210
22       1011220
23       1011230
24       1011240
25       1011250
26       1011260
27       1011270
28       1011280
29       1011290
          ...
32496    7202736
32497    7202746
32498    7202756
32499     720276
32500    7202766
32501    7202776
32502    7202786
32503    7202796
32504    7202806
32505    7202816
32506    7202826
32507    7202836
32508    7202846
32509    7202856
32510     720286
32511    7202866
32512    7202876
32513    7202886
32514    7202896
32515    7202906
32516    7202916
32517    7202926
32518    7202936
32519    7202946
32520    7202956
32521     720296
32522    7202966
32523    7202976
32524    7202986
32525    7202996
Name: id, Length: 32408, dtype: int64

In [26]:
df.describe()

                 id    State_Code  ...          Stdev          sum_w
count  3.252600e+04  32526.000000  ...   32526.000000   32526.000000
mean   6.203707e+07     28.624885  ...   47273.695321     576.910273
std    1.115546e+08     16.297205  ...   16555.486882    3911.006939
min    1.026000e+03      1.000000  ...       0.000000       0.000000
25%    8.021282e+06     13.000000  ...   36075.000000     201.436458
50%    2.901168e+07     29.000000  ...   46179.000000     329.482618
75%    4.802899e+07     42.000000  ...   58078.000000     590.227670
max    4.802211e+08     72.000000  ...  113936.000000  612241.922964

[8 rows x 11 columns]